// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsVFQCmsoKIbyOTef-EYuUMtOUOFTvaOk',
    appId: '1:947546313629:web:fc64a1e3dadc662ff69574',
    messagingSenderId: '947546313629',
    projectId: 'pido-app',
    authDomain: 'pido-app.firebaseapp.com',
    storageBucket: 'pido-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsVFQCmsoKIbyOTef-EYuUMtOUOFTvaOk',
    appId: '1:947546313629:android:fc64a1e3dadc662ff69574',
    messagingSenderId: '947546313629',
    projectId: 'pido-app',
    storageBucket: 'pido-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA33Ykfv4RdlDsodY-5aZvJmQaHRK-_7B8',
    appId: '1:947546313629:ios:9cc6ea06d0687c64f69574',
    messagingSenderId: '947546313629',
    projectId: 'pido-app',
    storageBucket: 'pido-app.firebasestorage.app',
    iosBundleId: 'com.example.pidoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA33Ykfv4RdlDsodY-5aZvJmQaHRK-_7B8',
    appId: '1:947546313629:ios:9cc6ea06d0687c64f69574',
    messagingSenderId: '947546313629',
    projectId: 'pido-app',
    storageBucket: 'pido-app.firebasestorage.app',
    iosBundleId: 'com.example.pidoapp',
  );
}
